### PR TITLE
Make CI succeed again

### PR DESCRIPTION
**Pull request by webwarrior-ws**
Several changes made in order to make CI successfull:
- changed `runs-on` in `ci.yml` to `windows-2019`
- added pragmas to disable deprecation errors

### CODE REVIEW

**Comment by knocte** [comment]
@webwarrior-ws seems the 4 errors left are:

```
  D:\a\DotNetEssentials\DotNetEssentials\Xamarin.Essentials\DeviceInfo\DeviceInfo.macos.cs(30,24): error CS0618: 'NSString.FromHandle(IntPtr)' is obsolete: 'Use of 'CFString.FromHandle' offers better performance.' [D:\a\DotNetEssentials\DotNetEssentials\Xamarin.Essentials\Xamarin.Essentials.csproj]
  D:\a\DotNetEssentials\DotNetEssentials\Xamarin.Essentials\TextToSpeech\TextToSpeech.macos.cs(54,33): error CS0618: 'NSSpeechBoundary.hWord' is obsolete: 'Use 'Word' instead.' [D:\a\DotNetEssentials\DotNetEssentials\Xamarin.Essentials\Xamarin.Essentials.csproj]
  D:\a\DotNetEssentials\DotNetEssentials\Xamarin.Essentials\Platform\Platform.macos.cs(183,21): error CS0618: 'NSString.FromHandle(IntPtr)' is obsolete: 'Use of 'CFString.FromHandle' offers better performance.' [D:\a\DotNetEssentials\DotNetEssentials\Xamarin.Essentials\Xamarin.Essentials.csproj]
  D:\a\DotNetEssentials\DotNetEssentials\Xamarin.Essentials\Platform\Platform.macos.cs(248,25): error CS0618: 'NSString.FromHandle(IntPtr)' is obsolete: 'Use of 'CFString.FromHandle' offers better performance.' [D:\a\DotNetEssentials\DotNetEssentials\Xamarin.Essentials\Xamarin.Essentials.csproj]
```

Please have a look at upstream Xamarin.Essentials to see if the problem is already fixed there.

**Comment by knocte** [comment]
@webwarrior-ws another thing that comes to mind is that those errors look like warnings that have been promoted to errors; if I'm right then another thing to try is to disable warnings as errors to see if they are gone.

**Comment by webwarrior-ws** [comment]
Looks like in upstream they just added a bunch of `#pragma warning disable 0618` directives

**Comment by knocte** [comment]
> Looks like in upstream they just added a bunch of #pragma warning disable 0618 directives

Haha brilliant, then let's bring those here and in the commit message let's put the URL to the commit that fixes this in Xamarin.Essentials please.

**Comment by knocte** [comment]
> Haha brilliant, then let's bring those here and in the commit message let's put the URL to the commit that fixes this in Xamarin.Essentials please.

And given that the 2nd commit of this PR will not change the ci.yml file, then the PR details (title and description) need to be edited/updated.

**Comment by knocte** [comment]
@webwarrior-ws 2 more errors left to fix:

```

  D:\a\DotNetEssentials\DotNetEssentials\Samples\Samples.iOS\Main.cs(9,13): error CS0618: 'UIApplication.Main(string[]?, string?, string?)' is obsolete: 'Use the overload with 'Type' instead of 'String' parameters for type safety.' [D:\a\DotNetEssentials\DotNetEssentials\Samples\Samples.iOS\Samples.iOS.csproj]


"D:\a\DotNetEssentials\DotNetEssentials\Xamarin.Essentials.sln" (Build target) (1:2) ->
"D:\a\DotNetEssentials\DotNetEssentials\DeviceTests\DeviceTests.iOS\DeviceTests.iOS.csproj" (default target) (11:6) ->
  D:\a\DotNetEssentials\DotNetEssentials\DeviceTests\DeviceTests.iOS\Main.cs(9,13): error CS0618: 'UIApplication.Main(string[]?, string?, string?)' is obsolete: 'Use the overload with 'Type' instead of 'String' parameters for type safety.' [D:\a\DotNetEssentials\DotNetEssentials\DeviceTests\DeviceTests.iOS\DeviceTests.iOS.csproj]

```

**Pull request merged**
